// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvcH_j0VRlSVxZV6ezBsfBQyObhcDTvJE',
    appId: '1:968805889546:web:fd4acadb8121b116eb11f3',
    messagingSenderId: '968805889546',
    projectId: 'iuran-app-de7f9',
    authDomain: 'iuran-app-de7f9.firebaseapp.com',
    storageBucket: 'iuran-app-de7f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwQ5qtlP-fhs0kx9B0bfFQ3mrj-QcBJHY',
    appId: '1:968805889546:android:fb239d2c8c8f3d33eb11f3',
    messagingSenderId: '968805889546',
    projectId: 'iuran-app-de7f9',
    storageBucket: 'iuran-app-de7f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqqGu6Tk7EYPLTrpn86koQheHn0-FmMCA',
    appId: '1:968805889546:ios:769e4f2a94000a24eb11f3',
    messagingSenderId: '968805889546',
    projectId: 'iuran-app-de7f9',
    storageBucket: 'iuran-app-de7f9.firebasestorage.app',
    iosBundleId: 'com.example.iuranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqqGu6Tk7EYPLTrpn86koQheHn0-FmMCA',
    appId: '1:968805889546:ios:769e4f2a94000a24eb11f3',
    messagingSenderId: '968805889546',
    projectId: 'iuran-app-de7f9',
    storageBucket: 'iuran-app-de7f9.firebasestorage.app',
    iosBundleId: 'com.example.iuranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvcH_j0VRlSVxZV6ezBsfBQyObhcDTvJE',
    appId: '1:968805889546:web:cecc1e32e5f658daeb11f3',
    messagingSenderId: '968805889546',
    projectId: 'iuran-app-de7f9',
    authDomain: 'iuran-app-de7f9.firebaseapp.com',
    storageBucket: 'iuran-app-de7f9.firebasestorage.app',
  );
}
