name: iuran_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.7
  url_launcher: ^6.3.0
  http: ^1.6.0
  intl: ^0.20.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#F5F2EB"
  image: assets/logo/logo_apk.png

  android_12:
    color: "#F5F2EB"
    image: assets/logo/logo_apk.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/logo_apk.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700